name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install pytest
      run: pip install pytest

    - name: Run tests
      run: pytest

# Push to main or create a PR
# ↓
# Start workflow
# ↓
# Create Ubuntu VM
# ↓
# Checkout your code
# ↓
# Install Python
# ↓
# Install pytest
# ↓
# Run your tests
# ↓
# Show success/failure in GitHub Actions
